### ISSUE TITLE
G-Pooling

### ISSUE THREAD

**Issue by dqii** [ehoogeboom/hexaconv#3]
Is G-Pooling included in this implementation?

**Comment by ehoogeboom** [comment]
Hi Di,

If you are referring to the equivariant version of 2D pooling, then pooling is implemented for p4 & p4m (the standard pooling operation can be used). It is not implemented for p6(m), this requires the pooling operation to only consider elements in an hexagonal shape.

If you are referring to a pooling operation applied to the group itself, then pooling is not implemented.

Best,
Emiel

**Comment by tscohen** [comment]
My answer in the other repo applies here as well: https://github.com/tscohen/GrouPy/issues/9
